// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

var TableNames = struct {
	CodeFiles                string
	Projects                 string
	ProjectsCodeFilesHistory string
	ProjectsHistory          string
	ProjectsTags             string
	Tags                     string
}{
	CodeFiles:                "code_files",
	Projects:                 "projects",
	ProjectsCodeFilesHistory: "projects_code_files_history",
	ProjectsHistory:          "projects_history",
	ProjectsTags:             "projects_tags",
	Tags:                     "tags",
}
