// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("CodeFiles", testCodeFilesUpsert)

	t.Run("Projects", testProjectsUpsert)

	t.Run("ProjectsCodeFilesHistories", testProjectsCodeFilesHistoriesUpsert)

	t.Run("ProjectsHistories", testProjectsHistoriesUpsert)

	t.Run("ProjectsTags", testProjectsTagsUpsert)

	t.Run("Tags", testTagsUpsert)
}
