version: "3.9"
services:
  database_projects:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: projects
    ports:
      - 5432:5432
    volumes:
      - ./pkg/services/projects/store/data:/var/lib/postgresql/data
    networks:
      server:
       ipv4_address: 10.7.0.2
  server_projects:
    build:
      dockerfile: dockerfile
      context: .
    ports:
      - 80:8081
    volumes:
      - .:/app
    networks:
      server:
       ipv4_address: 10.7.0.3
networks:
  server:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.7.0.0/16
         gateway: 10.7.0.1